/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TallerIndexRouteImport } from './routes/taller.index'
import { Route as TallerPedidosRouteImport } from './routes/taller.pedidos'
import { Route as TallerPedidoRouteImport } from './routes/taller.pedido'
import { Route as TallerInscripcionRouteImport } from './routes/taller.inscripcion'
import { Route as TallerCuentaRouteImport } from './routes/taller.cuenta'
import { Route as TallerAccesoRouteImport } from './routes/taller.acceso'
import { Route as SitemapProductsPageRouteImport } from './routes/sitemap-products.$page'
import { Route as RepuestoSlugRouteImport } from './routes/repuesto.$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as TallerPedidosIndexRouteImport } from './routes/taller.pedidos.index'
import { Route as TallerPedidosIdRouteImport } from './routes/taller.pedidos.$id'
import { Route as TallerPedidoRecibidoRouteImport } from './routes/taller.pedido.recibido'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerIndexRoute = TallerIndexRouteImport.update({
  id: '/taller/',
  path: '/taller/',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerPedidosRoute = TallerPedidosRouteImport.update({
  id: '/taller/pedidos',
  path: '/taller/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerPedidoRoute = TallerPedidoRouteImport.update({
  id: '/taller/pedido',
  path: '/taller/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerInscripcionRoute = TallerInscripcionRouteImport.update({
  id: '/taller/inscripcion',
  path: '/taller/inscripcion',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerCuentaRoute = TallerCuentaRouteImport.update({
  id: '/taller/cuenta',
  path: '/taller/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerAccesoRoute = TallerAccesoRouteImport.update({
  id: '/taller/acceso',
  path: '/taller/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsPageRoute = SitemapProductsPageRouteImport.update({
  id: '/sitemap-products/$page',
  path: '/sitemap-products/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const RepuestoSlugRoute = RepuestoSlugRouteImport.update({
  id: '/repuesto/$slug',
  path: '/repuesto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerPedidosIndexRoute = TallerPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TallerPedidosRoute,
} as any)
const TallerPedidosIdRoute = TallerPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TallerPedidosRoute,
} as any)
const TallerPedidoRecibidoRoute = TallerPedidoRecibidoRouteImport.update({
  id: '/recibido',
  path: '/recibido',
  getParentRoute: () => TallerPedidoRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/repuesto/$slug': typeof RepuestoSlugRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/taller/acceso': typeof TallerAccesoRoute
  '/taller/cuenta': typeof TallerCuentaRoute
  '/taller/inscripcion': typeof TallerInscripcionRoute
  '/taller/pedido': typeof TallerPedidoRouteWithChildren
  '/taller/pedidos': typeof TallerPedidosRouteWithChildren
  '/taller/': typeof TallerIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/taller/pedido/recibido': typeof TallerPedidoRecibidoRoute
  '/taller/pedidos/$id': typeof TallerPedidosIdRoute
  '/taller/pedidos/': typeof TallerPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/repuesto/$slug': typeof RepuestoSlugRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/taller/acceso': typeof TallerAccesoRoute
  '/taller/cuenta': typeof TallerCuentaRoute
  '/taller/inscripcion': typeof TallerInscripcionRoute
  '/taller/pedido': typeof TallerPedidoRouteWithChildren
  '/taller': typeof TallerIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/taller/pedido/recibido': typeof TallerPedidoRecibidoRoute
  '/taller/pedidos/$id': typeof TallerPedidosIdRoute
  '/taller/pedidos': typeof TallerPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/legal': typeof LegalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/repuesto/$slug': typeof RepuestoSlugRoute
  '/sitemap-products/$page': typeof SitemapProductsPageRoute
  '/taller/acceso': typeof TallerAccesoRoute
  '/taller/cuenta': typeof TallerCuentaRoute
  '/taller/inscripcion': typeof TallerInscripcionRoute
  '/taller/pedido': typeof TallerPedidoRouteWithChildren
  '/taller/pedidos': typeof TallerPedidosRouteWithChildren
  '/taller/': typeof TallerIndexRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/taller/pedido/recibido': typeof TallerPedidoRecibidoRoute
  '/taller/pedidos/$id': typeof TallerPedidosIdRoute
  '/taller/pedidos/': typeof TallerPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/legal'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/repuesto/$slug'
    | '/sitemap-products/$page'
    | '/taller/acceso'
    | '/taller/cuenta'
    | '/taller/inscripcion'
    | '/taller/pedido'
    | '/taller/pedidos'
    | '/taller/'
    | '/api/whatsapp/webhook'
    | '/taller/pedido/recibido'
    | '/taller/pedidos/$id'
    | '/taller/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/legal'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/repuesto/$slug'
    | '/sitemap-products/$page'
    | '/taller/acceso'
    | '/taller/cuenta'
    | '/taller/inscripcion'
    | '/taller/pedido'
    | '/taller'
    | '/api/whatsapp/webhook'
    | '/taller/pedido/recibido'
    | '/taller/pedidos/$id'
    | '/taller/pedidos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/legal'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/health'
    | '/repuesto/$slug'
    | '/sitemap-products/$page'
    | '/taller/acceso'
    | '/taller/cuenta'
    | '/taller/inscripcion'
    | '/taller/pedido'
    | '/taller/pedidos'
    | '/taller/'
    | '/api/whatsapp/webhook'
    | '/taller/pedido/recibido'
    | '/taller/pedidos/$id'
    | '/taller/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogoRoute: typeof CatalogoRoute
  LegalRoute: typeof LegalRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  RepuestoSlugRoute: typeof RepuestoSlugRoute
  SitemapProductsPageRoute: typeof SitemapProductsPageRoute
  TallerAccesoRoute: typeof TallerAccesoRoute
  TallerCuentaRoute: typeof TallerCuentaRoute
  TallerInscripcionRoute: typeof TallerInscripcionRoute
  TallerPedidoRoute: typeof TallerPedidoRouteWithChildren
  TallerPedidosRoute: typeof TallerPedidosRouteWithChildren
  TallerIndexRoute: typeof TallerIndexRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/': {
      id: '/taller/'
      path: '/taller'
      fullPath: '/taller/'
      preLoaderRoute: typeof TallerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/pedidos': {
      id: '/taller/pedidos'
      path: '/taller/pedidos'
      fullPath: '/taller/pedidos'
      preLoaderRoute: typeof TallerPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/pedido': {
      id: '/taller/pedido'
      path: '/taller/pedido'
      fullPath: '/taller/pedido'
      preLoaderRoute: typeof TallerPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/inscripcion': {
      id: '/taller/inscripcion'
      path: '/taller/inscripcion'
      fullPath: '/taller/inscripcion'
      preLoaderRoute: typeof TallerInscripcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/cuenta': {
      id: '/taller/cuenta'
      path: '/taller/cuenta'
      fullPath: '/taller/cuenta'
      preLoaderRoute: typeof TallerCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/acceso': {
      id: '/taller/acceso'
      path: '/taller/acceso'
      fullPath: '/taller/acceso'
      preLoaderRoute: typeof TallerAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products/$page': {
      id: '/sitemap-products/$page'
      path: '/sitemap-products/$page'
      fullPath: '/sitemap-products/$page'
      preLoaderRoute: typeof SitemapProductsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repuesto/$slug': {
      id: '/repuesto/$slug'
      path: '/repuesto/$slug'
      fullPath: '/repuesto/$slug'
      preLoaderRoute: typeof RepuestoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller/pedidos/': {
      id: '/taller/pedidos/'
      path: '/'
      fullPath: '/taller/pedidos/'
      preLoaderRoute: typeof TallerPedidosIndexRouteImport
      parentRoute: typeof TallerPedidosRoute
    }
    '/taller/pedidos/$id': {
      id: '/taller/pedidos/$id'
      path: '/$id'
      fullPath: '/taller/pedidos/$id'
      preLoaderRoute: typeof TallerPedidosIdRouteImport
      parentRoute: typeof TallerPedidosRoute
    }
    '/taller/pedido/recibido': {
      id: '/taller/pedido/recibido'
      path: '/recibido'
      fullPath: '/taller/pedido/recibido'
      preLoaderRoute: typeof TallerPedidoRecibidoRouteImport
      parentRoute: typeof TallerPedidoRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TallerPedidoRouteChildren {
  TallerPedidoRecibidoRoute: typeof TallerPedidoRecibidoRoute
}

const TallerPedidoRouteChildren: TallerPedidoRouteChildren = {
  TallerPedidoRecibidoRoute: TallerPedidoRecibidoRoute,
}

const TallerPedidoRouteWithChildren = TallerPedidoRoute._addFileChildren(
  TallerPedidoRouteChildren,
)

interface TallerPedidosRouteChildren {
  TallerPedidosIdRoute: typeof TallerPedidosIdRoute
  TallerPedidosIndexRoute: typeof TallerPedidosIndexRoute
}

const TallerPedidosRouteChildren: TallerPedidosRouteChildren = {
  TallerPedidosIdRoute: TallerPedidosIdRoute,
  TallerPedidosIndexRoute: TallerPedidosIndexRoute,
}

const TallerPedidosRouteWithChildren = TallerPedidosRoute._addFileChildren(
  TallerPedidosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogoRoute: CatalogoRoute,
  LegalRoute: LegalRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  RepuestoSlugRoute: RepuestoSlugRoute,
  SitemapProductsPageRoute: SitemapProductsPageRoute,
  TallerAccesoRoute: TallerAccesoRoute,
  TallerCuentaRoute: TallerCuentaRoute,
  TallerInscripcionRoute: TallerInscripcionRoute,
  TallerPedidoRoute: TallerPedidoRouteWithChildren,
  TallerPedidosRoute: TallerPedidosRouteWithChildren,
  TallerIndexRoute: TallerIndexRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
